version: '3.3'

services:
  qserver:
    build:
      context: ./
      dockerfile: Dockerfile
    image: qserver
    restart: always
    container_name: qserver
    hostname: qserver.local
    privileged: true
    networks:
      - qnetwork


  qapi:
    build:
      context: ./qapi/
      dockerfile: Dockerfile
    image: qapi
    restart: always
    container_name: qapi
    hostname: qapi.local
    environment:
      API_KEY: qwezxc1234
    networks:
      - qnetwork
    ports:
      - "443:443"
#  mysql:
#    image: hypriot/rpi-mysql
#    restart: always
#    container_name: mysql
#    volumes:
#      - "/home/pi:/var/lib/mysql"
#    hostname: mysql.local
#    user: root
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=ledger
#      - MYSQL_USER=collector
#      - MYSQL_USER=collector.Passwd.1
#    networks:
#      - qnetwork

networks:
  qnetwork: